ethereum_rpc = "https://rpc.mevblocker.io"
drosera_rpc = "https://relay.ethereum.drosera.io/"
eth_chain_id = 1
drosera_address = "0x01C344b8406c3237a6b9dbd06ef2832142866d87"

[traps.bybit_safe_trap]
path = "out/BybitSafeTrap.sol/BybitSafeTrap.json"
response_contract = "0x52d24A32B8d9F4B771c835e5178807d93352539D" # Set to deployed SafeGuardResponder address
response_function = "emergencyPause(address,address,uint8)"
cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 5
block_sample_size = 10
private_trap = true
whitelist = ["0x8944e2090Ccbce53dEc8F503126ca04A43D8CDE2"]
