ethereum_rpc = "https://eth.drpc.org"
drosera_rpc = "https://relay.ethereum.drosera.io/"
eth_chain_id = 1
drosera_address = "0x01C344b8406c3237a6b9dbd06ef2832142866d87"

[traps.bybit_safe_trap_v2]
path = "out/BybitSafeTrapV2.sol/BybitSafeTrapV2.json"
response_contract = "0xYOUR_RESPONDER_V2"
response_function = "handleIncident(bytes)"
cooldown_period_blocks = 20
min_number_of_operators = 3
max_number_of_operators = 7
block_sample_size = 10
private_trap = true
whitelist = ["0x8944e2090Ccbce53dEc8F503126ca04A43D8CDE2","0x2a3080AA52DE07702dd30b81cC97C3527e605B6A"]
